export const INVESTMENT_LIST_REQUEST = 'INVESTMENT_LIST_REQUEST';
export const INVESTMENT_LIST_SUCCESS = 'INVESTMENT_LIST_SUCCESS';
export const INVESTMENT_LIST_FAIL = 'INVESTMENT_LIST_FAIL';
export const INVESTMENT_CREATE_REQUEST = 'INVESTMENT_CREATE_REQUEST';
export const INVESTMENT_CREATE_SUCCESS = 'INVESTMENT_CREATE_SUCCESS';
export const INVESTMENT_CREATE_FAIL = 'INVESTMENT_CREATE_FAIL';
